[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name              tail
    Path              /var/log/*.log
    Tag               linux.logs
    Read_from_Head    False
    Refresh_Interval  5
    Skip_Long_Lines   On

[OUTPUT]
    Name              opentelemetry
    Match             linux.logs
    Host              127.0.0.1
    Port              4318
    URI               /v1/logs
    TLS               Off
