groups:
  - name: linux-production-platform
    rules:

      - alert: InstanceDown
        expr: up == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Monitoring target is down"

      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "CPU usage is above 85%"

      - alert: HighMemoryUsage
        expr: |
          (
            1 -
            node_memory_MemAvailable_bytes /
            node_memory_MemTotal_bytes
          ) * 100 > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Memory usage is above 90%"
